GCC := gcc
FLAGS := -std=c99 -Wall -Werror -D EXPORTS -ggdb
OBJF := arr_fib_lib.o del_reps_lib.o check.o

%.o : %.c *.h
	$(GCC) $(FLAGS) -c $<

arr_fib_lib.dll: arr_fib_lib.o
	$(GCC) -shared arr_fib_lib.o -Wl,--subsystem,windows -o arr_fib_lib.dll

del_reps_lib.dll: del_reps_lib.o
	$(GCC) -shared del_reps_lib.o -Wl,--subsystem,windows -o del_reps_lib.dll

app.exe : $(OBJF) test.o
	$(GCC) $^ -L. $(LIBF) -o $@

clean :
	rm *.o *dll *.exe
