CC := gcc

CFLAGS := -std=c99 -Wall -Werror -pedantic



%.o : %.c *.h
	
	$(CC) $(CFLAGS) -c $<



list.exe : test.o dequeue_n_enqueue_test.o enqueue_test.o dequeue_test.o queue_list.o
	
	$(CC) $^ -o $@



array.exe : test.o dequeue_n_enqueue_test.o enqueue_test.o dequeue_test.o queue_array.o
	
	$(CC) $^ -o $@



clean : 
	
	rm *.o *.exe