GCC := gcc
FLAGS := -std=c99 -Wall -Werror -ggdb
OBJF := libkey.a libmysort.a keytest.o mysorttest.o main_func.o
LIBF := -lmysort -lkey


%.o : %.c *.h
	$(GCC) $(FLAGS) -c $<

lib%.a : %_lib.o
	ar rc $@ $^
	ranlib $@


app.exe : $(OBJF) main.o
	$(GCC) $^ -L. $(LIBF) -o $@

test.exe : $(OBJF) test.o
	$(GCC) $^ -L. $(LIBF) -o $@

clean :
	rm *.o *.exe *.a
